# Generated by Django 5.1.1 on 2024-09-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitestatistics',
            name='last_accessed',
        ),
        migrations.AlterField(
            model_name='sitestatistics',
            name='data_received',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sitestatistics',
            name='data_sent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sitestatistics',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.site'),
        ),
    ]
