# Generated by Django 5.1.1 on 2024-09-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_sitestatistics_last_accessed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='data_received',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='site',
            name='data_sent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='site',
            name='transitions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SiteStatistics',
        ),
    ]
